In [1]:
import pandas as pd


#read json file
df = pd.read_json('/scratch/user/atharvchagi_tamu.edu/dllm_fork/logs/eval_generations/__scratch__user__atharvchagi_tamu.edu__dllm_fork__models__a2d__Qwen3-0.6B-diffusion-bd3lm-v0.1__bd3lm__sft-full-mix__2048_batch_size__checkpoint-final/samples_hendrycks_math500_2026-03-23T13-08-51.008354.jsonl', lines=True)

In [2]:
df

,doc_id,doc,target,arguments,resps,filtered_resps,filter,metrics,doc_hash,prompt_hash,target_hash,exact_match
0,0,"{'problem': 'Convert the point $(0,3)$ in rect...","\left( 3, \frac{\pi}{2} \right)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[We are given the point $(0, 3)$ in **rectang...","[We are given the point $(0, 3)$ in **rectangu...",create_test,[exact_match],c19ad5e1bd748992de8b92006c4ebc5f74a4bf83d3f0b7...,fb5fb0ede4e5c658ea4bff887b7d1104d07e8d00fcbe23...,9830c3250b9d5e11cd6edc430fb1398d3afda84b4ab4be...,0
1,8,"{'problem': 'What is the distance, in units, b...",3\sqrt{13},{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are to find the **distance** between two ...,[We are to find the **distance** between two p...,create_test,[exact_match],9635515d3e4d23644e4ac149f6ca50341c0bbda7d0e121...,13dd662beb9c345ec0bd617e7e1a5351445fd12745c460...,8081f877c1797b6f58a9f2c55a25dbf6720bf2e54adcd3...,0
2,16,{'problem': 'Compute: $1-2+3-4+5- \dots +99-10...,-50,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are asked to compute the following expres...,[We are asked to compute the following express...,create_test,[exact_match],13bad6df5aee4db1a4f1b96f6693173869f719af7b27d5...,bec960fa7eefa53f261ab397e8a74e706f048ad67eeac5...,2fb999c7eb9fd71a9b6ef0ea40953481f9edaee5beff42...,0
3,24,{'problem': 'A worker receives an annual wage ...,10,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given:\n\n- **Initial annual annual w...,[We are given:\n\n- **Initial annual annual wa...,create_test,[exact_match],fa2e8ef687de27927733ea720b34614163e45b41a42626...,2249ae8b884a5490e694468f636cca0f24286c6e383fc0...,4a44dc15364204a80fe80e9039455cc1608281820fe2b2...,0
4,32,{'problem': 'In how many ways can 8 people sit...,720,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given:\n\n- 8 people in total.\n- 3 o...,[We are given:\n\n- 8 people in total.\n- 3 of...,create_test,[exact_match],d7bdfb4afbf6c1ba070c963732c8025e074be7a00c2831...,1dbf4211462a8cd203d6fe846c41a38a35bcda47e4f69c...,d829857eb1366e70be857a69886d1555af0d32681beab0...,0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,463,{'problem': 'For how many values of $x$ is the...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the expression:\n\n$$\n\frac{x ...,[2],create_test,[exact_match],826b260094444f41a284006913f17558ecb66a92c38d5f...,817016fe88ff1a9397f5b3d2104a6398fb6cd6ba3d8a01...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1
496,471,{'problem': 'A class of 30 students recently t...,84,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To find the class average (mean), we need to...",[84],create_test,[exact_match],775e99adfca672293b8435861dec82328c8dda9751835a...,9a69468c0ed4d3823bfb388a87ef77aa0d6e998f238484...,44c8031cb036a7350d8b9b8603af662a4b9cdbd2f96e8d...,1
497,479,{'problem': 'There are finitely many primes $p...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the congruence:\n\n$$\n8x \equi...,[We are given the congruence:\n\n$$\n8x \equiv...,create_test,[exact_match],a821d8254a09fd6ed67a0aa9048e31c242423b10acc5c1...,9f361df9077b35bbe6ceae78c3004de1160a32045b9e84...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0
498,487,{'problem': 'Determine the modulo 4 remainder ...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are asked to find the **modulo 4 remainde...,[We are asked to find the **modulo 4 remainder...,create_test,[exact_match],2340b88d813c833744796cbba951ec6d9e407d5de35183...,9173f6793453c5e1be3274dfeab576c5d572d9a49b794b...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0
499,495,{'problem': 'What is the domain of the functio...,"(2,12) \cup (12,102)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the function:\n\n$$\nf(x) = \fr...,[We are given the function:\n\n$$\nf(x) = \fra...,create_test,[exact_match],cbd1f436b63535495ba755c6070d5874fa6ce4e60456a4...,a76fc0e8419b9187fa24e5d4165c2a1048b7f1bc529153...,0cc05a283256d9d4540b3a48c2079841151234b449f75c...,0

In [26]:
import re

# Count how many times "we" appears as a standalone word in generation text
def _flatten_text(x):
    if isinstance(x, str):
        return x
    if isinstance(x, list):
        return " ".join(_flatten_text(v) for v in x)
    if isinstance(x, dict):
        return " ".join(_flatten_text(v) for v in x.values())
    return str(x)

df["we_count"] = df["resps"].apply(
    lambda x: len(re.findall(r"\bwe\b", _flatten_text(x).lower()))
)

In [ ]:
df

,doc_id,doc,target,arguments,resps,filtered_resps,filter,metrics,doc_hash,prompt_hash,target_hash,exact_match,we_count
0,0,"{'problem': 'Convert the point $(0,3)$ in rect...","\left( 3, \frac{\pi}{2} \right)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[We are given the point $(0, 3)$ in **rectang...","[We are given the point $(0, 3)$ in **rectangu...",create_test,[exact_match],c19ad5e1bd748992de8b92006c4ebc5f74a4bf83d3f0b7...,fb5fb0ede4e5c658ea4bff887b7d1104d07e8d00fcbe23...,9830c3250b9d5e11cd6edc430fb1398d3afda84b4ab4be...,0,2
1,8,"{'problem': 'What is the distance, in units, b...",3\sqrt{13},{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are to find the **distance** between two ...,[We are to find the **distance** between two p...,create_test,[exact_match],9635515d3e4d23644e4ac149f6ca50341c0bbda7d0e121...,13dd662beb9c345ec0bd617e7e1a5351445fd12745c460...,8081f877c1797b6f58a9f2c55a25dbf6720bf2e54adcd3...,0,1
2,16,{'problem': 'Compute: $1-2+3-4+5- \dots +99-10...,-50,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are asked to compute the following expres...,[We are asked to compute the following express...,create_test,[exact_match],13bad6df5aee4db1a4f1b96f6693173869f719af7b27d5...,bec960fa7eefa53f261ab397e8a74e706f048ad67eeac5...,2fb999c7eb9fd71a9b6ef0ea40953481f9edaee5beff42...,0,2
3,24,{'problem': 'A worker receives an annual wage ...,10,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given:\n\n- **Initial annual annual w...,[We are given:\n\n- **Initial annual annual wa...,create_test,[exact_match],fa2e8ef687de27927733ea720b34614163e45b41a42626...,2249ae8b884a5490e694468f636cca0f24286c6e383fc0...,4a44dc15364204a80fe80e9039455cc1608281820fe2b2...,0,3
4,32,{'problem': 'In how many ways can 8 people sit...,720,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given:\n\n- 8 people in total.\n- 3 o...,[We are given:\n\n- 8 people in total.\n- 3 of...,create_test,[exact_match],d7bdfb4afbf6c1ba070c963732c8025e074be7a00c2831...,1dbf4211462a8cd203d6fe846c41a38a35bcda47e4f69c...,d829857eb1366e70be857a69886d1555af0d32681beab0...,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,463,{'problem': 'For how many values of $x$ is the...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the expression:\n\n$$\n\frac{x ...,[2],create_test,[exact_match],826b260094444f41a284006913f17558ecb66a92c38d5f...,817016fe88ff1a9397f5b3d2104a6398fb6cd6ba3d8a01...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1,3
496,471,{'problem': 'A class of 30 students recently t...,84,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To find the class average (mean), we need to...",[84],create_test,[exact_match],775e99adfca672293b8435861dec82328c8dda9751835a...,9a69468c0ed4d3823bfb388a87ef77aa0d6e998f238484...,44c8031cb036a7350d8b9b8603af662a4b9cdbd2f96e8d...,1,1
497,479,{'problem': 'There are finitely many primes $p...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the congruence:\n\n$$\n8x \equi...,[We are given the congruence:\n\n$$\n8x \equiv...,create_test,[exact_match],a821d8254a09fd6ed67a0aa9048e31c242423b10acc5c1...,9f361df9077b35bbe6ceae78c3004de1160a32045b9e84...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,2
498,487,{'problem': 'Determine the modulo 4 remainder ...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are asked to find the **modulo 4 remainde...,[We are asked to find the **modulo 4 remainder...,create_test,[exact_match],2340b88d813c833744796cbba951ec6d9e407d5de35183...,9173f6793453c5e1be3274dfeab576c5d572d9a49b794b...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,2
499,495,{'problem': 'What is the domain of the functio...,"(2,12) \cup (12,102)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We are given the function:\n\n$$\nf(x) = \fr...,[We are given the function:\n\n$$\nf(x) = \fra...,create_test,[exact_match],cbd1f436b63535495ba755c6070d5874fa6ce4e60456a4...,a76fc0e8419b9187fa24e5d4165c2a1048b7f1bc529153...,0cc05a283256d9d4540b3a48c2079841151234b449f75c...,0,6

In [21]:
idx =62

df['resps'][idx]

[['To solve the math problem, we need to do the following:\n\n1 **Define the problem:**\n   - Let $ z = 1 + i $   → $ z $  1 + i $\n   - Let $ w = \\dfrac{3z + 1}{5z + 7} $ → $ w $ (3z + 1 / (5z + 7)\n   - Find $ |w| $**\n\n2 **Use the given data:**\n   - $ z = 1 + i $   → $ z $  1 + i $\n   - $ w = \\dfrac{3z + 1}{5z + 7} $ → $ w $ (3z + 1 / (5z + 7)\n   - Find $ |w| $**\n\n. **Step the solution:**\n   - Understand the problem and solve the math problem.\n   - Use the given data to find the value of $ |w| $.\n   - **Final Answer:**\n\n']]

In [24]:
df2 = pd.read_json('/scratch/user/atharvchagi_tamu.edu/dllm_fork/logs/eval_generations/dllm-hub__Qwen3-0.6B-diffusion-bd3lm-v0.1/samples_hendrycks_math500_2026-03-23T13-14-57.783783.jsonl', lines=True)

In [25]:
df2

,doc_id,doc,target,arguments,resps,filtered_resps,filter,metrics,doc_hash,prompt_hash,target_hash,exact_match
0,0,"{'problem': 'Convert the point $(0,3)$ in rect...","\left( 3, \frac{\pi}{2} \right)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the polar coordinates of the point $...,[To find the polar coordinates of the point $(...,create_test,[exact_match],c19ad5e1bd748992de8b92006c4ebc5f74a4bf83d3f0b7...,fb5fb0ede4e5c658ea4bff887b7d1104d07e8d00fcbe23...,9830c3250b9d5e11cd6edc430fb1398d3afda84b4ab4be...,0
1,8,"{'problem': 'What is the distance, in units, b...",3\sqrt{13},{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the distance between two points $(x1...,"[To find the distance between two points $(x1,...",create_test,[exact_match],9635515d3e4d23644e4ac149f6ca50341c0bbda7d0e121...,13dd662beb9c345ec0bd617e7e1a5351445fd12745c460...,8081f877c1797b6f58a9f2c55a25dbf6720bf2e54adcd3...,0
2,16,{'problem': 'Compute: $1-2+3-4+5- \dots +99-10...,-50,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We can rewrite the expression as $(1-2) + (3...,[-1],create_test,[exact_match],13bad6df5aee4db1a4f1b96f6693173869f719af7b27d5...,bec960fa7eefa53f261ab397e8a74e706f048ad67eeac5...,2fb999c7eb9fd71a9b6ef0ea40953481f9edaee5beff42...,0
3,24,{'problem': 'A worker receives an annual wage ...,10,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to determine ...","[To solve this problem, we need to determine t...",create_test,[exact_match],fa2e8ef687de27927733ea720b34614163e45b41a42626...,2249ae8b884a5490e694468f636cca0f24286c6e383fc0...,4a44dc15364204a80fe80e9039455cc1608281820fe2b2...,0
4,32,{'problem': 'In how many ways can 8 people sit...,720,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[First, we consider the 3 people Pierre, Rosa...","[First, we consider the 3 people Pierre, Rosa,...",create_test,[exact_match],d7bdfb4afbf6c1ba070c963732c8025e074be7a00c2831...,1dbf4211462a8cd203d6fe846c41a38a35bcda47e4f69c...,d829857eb1366e70be857a69886d1555af0d32681beab0...,0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,463,{'problem': 'For how many values of $x$ is the...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To determine for how many values of \(x\) is...,[To determine for how many values of \(x\) is ...,create_test,[exact_match],826b260094444f41a284006913f17558ecb66a92c38d5f...,817016fe88ff1a9397f5b3d2104a6398fb6cd6ba3d8a01...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0
496,471,{'problem': 'A class of 30 students recently t...,84,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To find the class average, we need to add up...",[final answer is 30.],create_test,[exact_match],775e99adfca672293b8435861dec82328c8dda9751835a...,9a69468c0ed4d3823bfb388a87ef77aa0d6e998f238484...,44c8031cb036a7350d8b9b8603af662a4b9cdbd2f96e8d...,0
497,479,{'problem': 'There are finitely many primes $p...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to identify t...","[To solve this problem, we need to identify th...",create_test,[exact_match],a821d8254a09fd6ed67a0aa9048e31c242423b10acc5c1...,9f361df9077b35bbe6ceae78c3004de1160a32045b9e84...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0
498,487,{'problem': 'Determine the modulo 4 remainder ...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to calculate ...","[To solve this problem, we need to calculate t...",create_test,[exact_match],2340b88d813c833744796cbba951ec6d9e407d5de35183...,9173f6793453c5e1be3274dfeab576c5d572d9a49b794b...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0
499,495,{'problem': 'What is the domain of the functio...,"(2,12) \cup (12,102)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the domain of the function $f(x) = \...,[To find the domain of the function $f(x) = \f...,create_test,[exact_match],cbd1f436b63535495ba755c6070d5874fa6ce4e60456a4...,a76fc0e8419b9187fa24e5d4165c2a1048b7f1bc529153...,0cc05a283256d9d4540b3a48c2079841151234b449f75c...,0

In [27]:
df2["we_count"] = df["resps"].apply(
    lambda x: len(re.findall(r"\bwe\b", _flatten_text(x).lower()))
)

In [28]:
df2

,doc_id,doc,target,arguments,resps,filtered_resps,filter,metrics,doc_hash,prompt_hash,target_hash,exact_match,we_count
0,0,"{'problem': 'Convert the point $(0,3)$ in rect...","\left( 3, \frac{\pi}{2} \right)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the polar coordinates of the point $...,[To find the polar coordinates of the point $(...,create_test,[exact_match],c19ad5e1bd748992de8b92006c4ebc5f74a4bf83d3f0b7...,fb5fb0ede4e5c658ea4bff887b7d1104d07e8d00fcbe23...,9830c3250b9d5e11cd6edc430fb1398d3afda84b4ab4be...,0,2
1,8,"{'problem': 'What is the distance, in units, b...",3\sqrt{13},{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the distance between two points $(x1...,"[To find the distance between two points $(x1,...",create_test,[exact_match],9635515d3e4d23644e4ac149f6ca50341c0bbda7d0e121...,13dd662beb9c345ec0bd617e7e1a5351445fd12745c460...,8081f877c1797b6f58a9f2c55a25dbf6720bf2e54adcd3...,0,1
2,16,{'problem': 'Compute: $1-2+3-4+5- \dots +99-10...,-50,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[We can rewrite the expression as $(1-2) + (3...,[-1],create_test,[exact_match],13bad6df5aee4db1a4f1b96f6693173869f719af7b27d5...,bec960fa7eefa53f261ab397e8a74e706f048ad67eeac5...,2fb999c7eb9fd71a9b6ef0ea40953481f9edaee5beff42...,0,2
3,24,{'problem': 'A worker receives an annual wage ...,10,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to determine ...","[To solve this problem, we need to determine t...",create_test,[exact_match],fa2e8ef687de27927733ea720b34614163e45b41a42626...,2249ae8b884a5490e694468f636cca0f24286c6e383fc0...,4a44dc15364204a80fe80e9039455cc1608281820fe2b2...,0,3
4,32,{'problem': 'In how many ways can 8 people sit...,720,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[First, we consider the 3 people Pierre, Rosa...","[First, we consider the 3 people Pierre, Rosa,...",create_test,[exact_match],d7bdfb4afbf6c1ba070c963732c8025e074be7a00c2831...,1dbf4211462a8cd203d6fe846c41a38a35bcda47e4f69c...,d829857eb1366e70be857a69886d1555af0d32681beab0...,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,463,{'problem': 'For how many values of $x$ is the...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To determine for how many values of \(x\) is...,[To determine for how many values of \(x\) is ...,create_test,[exact_match],826b260094444f41a284006913f17558ecb66a92c38d5f...,817016fe88ff1a9397f5b3d2104a6398fb6cd6ba3d8a01...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,3
496,471,{'problem': 'A class of 30 students recently t...,84,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To find the class average, we need to add up...",[final answer is 30.],create_test,[exact_match],775e99adfca672293b8435861dec82328c8dda9751835a...,9a69468c0ed4d3823bfb388a87ef77aa0d6e998f238484...,44c8031cb036a7350d8b9b8603af662a4b9cdbd2f96e8d...,0,1
497,479,{'problem': 'There are finitely many primes $p...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to identify t...","[To solve this problem, we need to identify th...",create_test,[exact_match],a821d8254a09fd6ed67a0aa9048e31c242423b10acc5c1...,9f361df9077b35bbe6ceae78c3004de1160a32045b9e84...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,2
498,487,{'problem': 'Determine the modulo 4 remainder ...,2,{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,"[[To solve this problem, we need to calculate ...","[To solve this problem, we need to calculate t...",create_test,[exact_match],2340b88d813c833744796cbba951ec6d9e407d5de35183...,9173f6793453c5e1be3274dfeab576c5d572d9a49b794b...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,2
499,495,{'problem': 'What is the domain of the functio...,"(2,12) \cup (12,102)",{'gen_args_0': {'arg_0': '<|im_start|>user Sol...,[[To find the domain of the function $f(x) = \...,[To find the domain of the function $f(x) = \f...,create_test,[exact_match],cbd1f436b63535495ba755c6070d5874fa6ce4e60456a4...,a76fc0e8419b9187fa24e5d4165c2a1048b7f1bc529153...,0cc05a283256d9d4540b3a48c2079841151234b449f75c...,0,6

In [32]:
#sum the we_count column
no_sft_we = df2["we_count"].sum()
sft_we = df['we_count'].sum()

In [33]:
print(no_sft_we, sft_we)

1606 1606

In [38]:
idx =4

print(f"Base BD3LM response: {df2['resps'][idx]}")
print(f"Teacher Data SFT response: {df['resps'][idx]}")

Base BD3LM response: [['First, we consider the 3 people Pierre, Rosa, and Thomas as a single entity. Now, we have 6 entities to arrange: the 3 people Pierre, Rosa, and Thomas, and the 5 other people. The number of ways to arrange these 6 entities is 6! = 720. However, since the people are around a round table, we need to divide by 6 to account for the rotations. Therefore, the number of unique arrangements is 120.']]
Teacher Data SFT response: [['We are given:\n\n- 8 people in total.\n- 3 of them: **Pierre, Rosa, and Thomas** **must all sit together**.\n- The rest: **Emily, Lisa, and Jack** can each sit in any of the remaining 5 people.\n- The **round table** is considered the same as a **rotation** of the arrangement.\n\nWe are to find the **number of distinct seatings** of the 8 people around the round table.\n\n---\n\n### Step 1: Treat the 3 fixed people as a single unit\n\nWe can treat the 3 fixed people as a **single unit** (let\'s call this the "block"").\n\nSo, we have:\n\n- 1 "block" (Pierre, Rosa, and Thomas)\n- 5 other free people (Emily, Lisa, Jack)\n\nSo, the total number of "units" to arrange is:\n\n$$\n1 \\text{ (the block)} + 5 \\text{ (other people)} = 6 \\text{ units}\n$$\n\n---\n\n### Step 2: Arrange the 6 units around the round table\n\nWhen arranging people around a round table, the number of distinct arrangements is:\n\n$$\n\\text{Number of arrangements} =']]